### ISSUE TITLE
Username vs. Nickname

### ISSUE THREAD

**Issue by mamazu** [Reix98/toysuitbot#7]
Users have user names and toys can have their toy names. However for the commands you need to know the user you are addressing (toy or not doesn't matter). And the bot also answers with user names.

Solution 1: Show the username next to the toy name for an easy look up.
Solution 2: Accept nicknames as well in the commands

**Comment by theogeer** [comment]
Solution 2 is probably good. Might also be a good thing to do !userList which would spit (to DM) a list of all users currently available and their status including the name(s) that you can reference them by

**Comment by mamazu** [comment]
Btw: Is there currently a check for duplicate nicknames? So something like "Sorry this nick name is already taken"
